const WHATSAPP="5599992283927",BUCKET="product-images";let sb=null,products=[],settings={},cart=[],cat="Todos",user=null;
const $=id=>document.getElementById(id), money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const DEFAULT_SUPABASE_URL="https://otidnzewlimycojxmseq.supabase.co";
const DEFAULT_SUPABASE_ANON="sb_publishable_QpJ4F_WQG9_7_GCZnL_2dg_HvZDT-ts";
function cfg(){return{url:localStorage.LOTUS_SUPABASE_URL||DEFAULT_SUPABASE_URL,anon:localStorage.LOTUS_SUPABASE_ANON||DEFAULT_SUPABASE_ANON}}
function init(){const c=cfg();if(!c.url||!c.anon)return false;sb=supabase.createClient(c.url,c.anon);return true}
function mode(m){const a=m==="admin";$("publicView").classList.toggle("hidden",a);$("adminView").classList.toggle("hidden",!a);$("cart").classList.toggle("hidden",a);if(a)prepAdmin()}
async function prepAdmin(){const ok=init();$("configBox").classList.toggle("hidden",ok);$("loginBox").classList.toggle("hidden",!ok);if(!ok)return;const {data}=await sb.auth.getUser();user=data?.user||null;adminState()}
function adminState(){const ok=!!user;$("loginBox").classList.toggle("hidden",ok);$("adminBox").classList.toggle("hidden",!ok);$("logout").classList.toggle("hidden",!ok);if(ok)loadAll()}
async function loadAll(){await loadSettings();await loadProducts()}
async function loadSettings(){if(!sb&&!init())return;const {data,error}=await sb.from("settings").select("*").eq("id",1).single();if(!error&&data)settings=data;applySettings()}
function applySettings(){ $("publicTitle").textContent=settings.title||"Lótus Confeitaria";$("publicSubtitle").textContent=settings.subtitle||"Doces artesanais, bolos e encomendas especiais.";$("bannerTitle").textContent=settings.banner_title||"Monte seu pedido online";$("bannerText").textContent=settings.banner_text||"Escolha os produtos e finalize no WhatsApp.";["settingTitle","settingSubtitle","settingBannerTitle","settingBannerText"].forEach(id=>{if($(id)) $(id).value={settingTitle:settings.title,settingSubtitle:settings.subtitle,settingBannerTitle:settings.banner_title,settingBannerText:settings.banner_text}[id]||""})}
async function saveSettings(){const payload={id:1,title:$("settingTitle").value,subtitle:$("settingSubtitle").value,banner_title:$("settingBannerTitle").value,banner_text:$("settingBannerText").value};const {error}=await sb.from("settings").upsert(payload);if(error)return alert("Erro ao salvar textos.");settings=payload;applySettings();alert("Textos salvos!")}
async function loadProducts(){if(!sb&&!init()){renderAll();return}const {data,error}=await sb.from("products").select("*").order("created_at",{ascending:false});if(error){alert("Erro ao carregar produtos. Confira SQL/RLS no Supabase.");console.error(error);return}products=data||[];renderAll()}
function renderAll(){renderCats();renderProducts();renderCart();renderAdmin();renderDashboard()}
function categories(){return [...new Set(products.map(p=>p.category).filter(Boolean))]}
function renderCats(){const cats=["Todos",...categories()];$("cats").innerHTML="";$("categoryList").innerHTML="";categories().forEach(c=>{let o=document.createElement("option");o.value=c;$("categoryList").appendChild(o)});cats.forEach(c=>{let b=document.createElement("button");b.className="cat"+(c===cat?" active":"");b.textContent=c;b.onclick=()=>{cat=c;renderCats();renderProducts()};$("cats").appendChild(b)})}
function productCard(p){return `${p.featured?'<div class="featured-tag">Destaque</div>':""}${p.image_url?`<img src="${p.image_url}">`:`<div class="ph">Foto do produto</div>`}<div class="body"><h3>${p.name}</h3><p>${p.description||"Sem descrição."}</p><small>${p.category||""}</small><div class="price">${money(p.price)}</div>${p.available?`<div class="qty"><input id="q-${p.id}" type="number" min="1" value="1"><button class="btn" onclick="addCart('${p.id}')">Adicionar</button></div>`:`<button class="btn light" disabled>Indisponível</button>`}</div>`}
function renderProducts(){let term=($("search").value||"").toLowerCase();let list=cat==="Todos"?products:products.filter(p=>p.category===cat);if(term)list=list.filter(p=>(p.name||"").toLowerCase().includes(term)||(p.description||"").toLowerCase().includes(term)||(p.category||"").toLowerCase().includes(term));let featured=products.filter(p=>p.featured&&p.available).slice(0,4);$("featuredArea").innerHTML=featured.length&&cat==="Todos"&&!term?`<h3 class="featured-title">Produtos em destaque</h3><div class="grid">${featured.map(p=>`<div class="card">${productCard(p)}</div>`).join("")}</div>`:"";$("grid").innerHTML=list.length?"":"<p>Nenhum produto encontrado.</p>";list.forEach(p=>{let d=document.createElement("div");d.className="card";d.innerHTML=productCard(p);$("grid").appendChild(d)})}
function addCart(id){let q=Math.max(1,Number($("q-"+id).value||1));let e=cart.find(i=>i.id==id);if(e)e.qty+=q;else cart.push({id,qty:q});renderCart()}
function renderCart(){$("cartItems").innerHTML=cart.length?"":"<small>Nenhum item adicionado.</small>";let t=0;cart.forEach(i=>{let p=products.find(x=>x.id==i.id);if(!p)return;let s=Number(p.price)*i.qty;t+=s;let r=document.createElement("div");r.className="cartitem";r.innerHTML=`<span>${i.qty}x ${p.name}<br><b>${money(s)}</b></span><button onclick="remCart('${i.id}')">x</button>`;$("cartItems").appendChild(r)});$("total").textContent="Total: "+money(t)}
function remCart(id){cart=cart.filter(i=>i.id!=id);renderCart()}
function checkout(){if(!cart.length)return alert("Adicione um produto.");let name=$("customer").value.trim(),note=$("note").value.trim(),t=0,msg="Olá, Lótus Confeitaria! Gostaria de fazer este pedido:%0A%0A";if(name)msg+=`Nome: ${name}%0A%0A`;cart.forEach(i=>{let p=products.find(x=>x.id==i.id);if(!p)return;let s=Number(p.price)*i.qty;t+=s;msg+=`• ${i.qty}x ${p.name} - ${money(s)}%0A`});msg+=`%0ATotal: ${money(t)}`;if(note)msg+=`%0A%0AObservação: ${note}`;msg+="%0A%0AAguardo confirmação.";open(`https://wa.me/${WHATSAPP}?text=${msg}`,"_blank")}
async function login(){let email=$("email").value.trim(),password=$("password").value;let {data,error}=await sb.auth.signInWithPassword({email,password});if(error)return alert("Login não autorizado.");user=data.user;adminState()}
async function logout(){await sb.auth.signOut();user=null;adminState()}
function saveConfig(){let url=$("supabaseUrl").value.trim(),anon=$("supabaseAnon").value.trim();if(!url||!anon)return alert("Preencha URL e anon key.");localStorage.LOTUS_SUPABASE_URL=url;localStorage.LOTUS_SUPABASE_ANON=anon;init();prepAdmin();loadAll()}
async function upload(file){if(!file)return"";let ext=file.name.split(".").pop(),path=`products/${Date.now()}-${Math.random().toString(16).slice(2)}.${ext}`;let {error}=await sb.storage.from(BUCKET).upload(path,file);if(error){alert("Erro ao enviar foto. Confira bucket público product-images.");console.error(error);return""}return sb.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}
async function saveProduct(e){e.preventDefault();let id=$("id").value,file=$("imageFile").files[0],img=await upload(file);let payload={name:$("name").value.trim(),category:$("category").value.trim(),price:Number($("price").value||0),description:$("description").value.trim(),available:$("available").value==="true",featured:$("featured").value==="true"};if(img)payload.image_url=img;let res=id?await sb.from("products").update(payload).eq("id",id):await sb.from("products").insert(payload);if(res.error){console.error(res.error);return alert("Erro ao salvar produto.")}$("form").reset();$("id").value="";await loadProducts();alert("Produto salvo!")}
function renderAdmin(){$("adminList").innerHTML="";products.forEach(p=>{let d=document.createElement("div");d.className="adminitem";d.innerHTML=`${p.image_url?`<img src="${p.image_url}">`:`<div class="mini">Sem foto</div>`}<div><b>${p.name}</b><br><small>${p.category} • ${money(p.price)} • ${p.available?"Disponível":"Indisponível"} ${p.featured?"• Destaque":""}</small></div><div><button class="btn light" onclick="edit('${p.id}')">Editar</button><button class="btn danger" onclick="del('${p.id}')">Excluir</button></div>`;$("adminList").appendChild(d)})}
function renderDashboard(){$("dashProducts").textContent=products.length;$("dashCategories").textContent=categories().length;$("dashFeatured").textContent=products.filter(p=>p.featured).length}
function edit(id){let p=products.find(x=>x.id==id);if(!p)return;$("id").value=p.id;$("name").value=p.name||"";$("category").value=p.category||"";$("price").value=p.price||0;$("description").value=p.description||"";$("available").value=String(!!p.available);$("featured").value=String(!!p.featured);scrollTo({top:0,behavior:"smooth"})}
async function del(id){if(!confirm("Excluir produto?"))return;let {error}=await sb.from("products").delete().eq("id",id);if(error)return alert("Erro ao excluir.");loadProducts()}
function exportJson(){let blob=new Blob([JSON.stringify(products,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="backup-produtos-lotus.json";a.click();URL.revokeObjectURL(url)}
function importJson(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=async()=>{try{let data=JSON.parse(r.result);if(!Array.isArray(data))throw Error();for(const p of data){await sb.from("products").insert({name:p.name,category:p.category,price:p.price,description:p.description,available:p.available??true,featured:p.featured??false,image_url:p.image_url||null})}await loadProducts();alert("Backup importado!")}catch{alert("Arquivo inválido.")}};r.readAsText(file)}
$("btnPublic").onclick=()=>mode("public");$("btnAdmin").onclick=()=>mode("admin");$("saveConfig").onclick=saveConfig;$("login").onclick=login;$("logout").onclick=logout;$("form").onsubmit=saveProduct;$("clear").onclick=()=>{$("form").reset();$("id").value=""};$("search").oninput=renderProducts;$("checkout").onclick=checkout;$("clearCart").onclick=()=>{cart=[];renderCart()};$("saveSettings").onclick=saveSettings;$("exportJson").onclick=exportJson;$("importJson").onchange=importJson;
if(init())loadAll();else renderAll();